# Generated by Django 4.1 on 2023-07-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_nature', models.CharField(max_length=255)),
                ('company_size', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('remarks_str', models.TextField()),
                ('job_link', models.URLField()),
            ],
        ),
    ]
