# Generated by Django 4.1 on 2023-07-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_remove_job_salary_job_max_salary_job_min_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
